// <auto-generated />
using System;
using Fiap.Api.Residuos.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace Fiap.Api.Residuos.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Fiap.Api.Residuos.Models.LixeiraModel", b =>
                {
                    b.Property<int>("LixeiraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LixeiraId"));

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("capacidadeFull")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("LixeiraId");

                    b.ToTable("TBL_LIXEIRA", (string)null);
                });

            modelBuilder.Entity("Fiap.Api.Residuos.Models.MoradorModel", b =>
                {
                    b.Property<int>("MoradorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MoradorId"));

                    b.Property<int>("IdLixeira")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("MoradorName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("MoradorId");

                    b.HasIndex("IdLixeira");

                    b.ToTable("TBL_MORADOR", (string)null);
                });

            modelBuilder.Entity("Fiap.Api.Residuos.Models.NotificacaoModel", b =>
                {
                    b.Property<int>("NotificacaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificacaoId"));

                    b.Property<DateTime>("DataNotificacao")
                        .HasColumnType("date");

                    b.Property<string>("NotificacaoDescricao")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("NotificacaoId");

                    b.ToTable("TBL_NOTIFICACAO", (string)null);
                });

            modelBuilder.Entity("Fiap.Api.Residuos.Models.MoradorModel", b =>
                {
                    b.HasOne("Fiap.Api.Residuos.Models.LixeiraModel", "Lixeira")
                        .WithMany()
                        .HasForeignKey("IdLixeira")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lixeira");
                });
#pragma warning restore 612, 618
        }
    }
}
